baseURL = "https://stonyc.github.io/"
publishdir = "../stonyc.github.io"
languageCode = "en-us"
title = "Tony Chun"
theme = "minimal"
googleAnalytics = "UA-116926668-1"

[params]
    author = "Tony Chun"
    description = "Coding in chunks"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python", "r"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/chunk/"
    name = "Chunks"
    weight = 3
    
[[menu.main]]
    url = "https://github.com/stonyc/notebooks/"
    name = "Python"
    weight = 4
    
[[menu.main]]
    url = "/resume/"
    name = "Resume"
    weight = 5
    
[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:stonyc@umich.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/stonyc/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/stonyc/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/stonyc/"
    name = "linkedin"
    weight = 4
